# Generated by Django 3.1.2 on 2020-11-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_billingaddress_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='eircode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
