# Generated by Django 3.1.2 on 2020-11-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20201129_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='username', max_length=254),
            preserve_default=False,
        ),
    ]
