# Generated by Django 3.1.2 on 2020-10-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeSizeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=120)),
                ('tier', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3"'), ('4', '4"'), ('5', '5"'), ('6', '6"')], default='1', max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
