# Generated by Django 3.1.2 on 2020-11-09 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cakesizecategory_flavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('cake_category', models.CharField(choices=[(1, 'Novelty Cakes'), (2, 'Wedding Cakes'), (3, 'Corporate Cakes')], max_length=120)),
                ('tier', models.CharField(choices=[('none', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('cup cakes', 'cup cakes')], default='none', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('slug', models.SlugField(unique=True)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=120)),
                ('create_date', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('featured_cake', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=False)),
                ('cake_size', models.ManyToManyField(to='products.CakeSizeCategory')),
            ],
            options={
                'unique_together': {('title', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
