# Generated by Django 3.1.2 on 2020-10-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cakesizecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakesizecategory',
            name='tier',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3"'), ('4', '4"'), ('5', '5"'), ('6', '6"')], default='1', max_length=120),
        ),
    ]
