# Generated by Django 3.1.2 on 2020-10-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201023_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cake_size',
            field=models.ManyToManyField(to='products.CakeSizeCategory'),
        ),
        migrations.AlterField(
            model_name='cakesizecategory',
            name='tier',
            field=models.CharField(choices=[('none', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('cup cakes', 'cup cakes')], default='none', max_length=120),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='tier',
            field=models.CharField(choices=[('none', 'None'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('cup cakes', 'cup cakes')], default='none', max_length=120),
        ),
        migrations.AlterField(
            model_name='variation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(choices=[('8', '8'), ('10', '10'), ('12', '12'), ('6"/8"', '6"/8"'), ('6"/10"', '6"/10"'), ('8"/12"', '8"/12"'), ('8"/10"', '8"/10"'), ('4"/6"/8"', '4"/6"/8"'), ('6"/8"/10"', '6"/8"/10"'), ('4"/6"/8"/10"', '4"/6"/8"/10"'), ('6"/8"/10"/12"', '6"/8"/10"/12"'), ('120 cupcakes', '120 cupcakes'), ('90 cupcakes', '90 cupcakes'), ('60 cupcakes', '60 cupcakes'), ('48 cupcakes', '48 cupcakes'), ('36 cupcakes', '36 cupcakes'), ('24 cupcakes', '24 cupcakes')], default=None, max_length=120),
        ),
    ]
