# Generated by Django 3.1.2 on 2020-10-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201024_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='CakeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('tier', models.CharField(choices=[('0', 'Uncategorized'), ('novelty', 'Novelty Cakes'), ('wedding', 'Wedding Cakes'), ('corporate', 'Corporate Cakes')], default='0', max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
