# Generated by Django 3.1.2 on 2020-11-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavour',
            name='category',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'basic'), ('cupcake', 'cupcake')], default='none', max_length=120),
        ),
    ]
