# Generated by Django 3.1.2 on 2020-11-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_flavour_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavourCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flavour',
            name='category',
        ),
        migrations.AddField(
            model_name='flavour',
            name='category',
            field=models.ManyToManyField(to='products.FlavourCategory'),
        ),
    ]
