# Generated by Django 3.1.2 on 2020-10-24 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cakecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cakecategory',
            old_name='tier',
            new_name='category',
        ),
    ]
