# Generated by Django 3.1.2 on 2020-10-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201024_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='product',
            name='cake_category',
            field=models.CharField(choices=[('Drip Cake Collection', 'Drip Cake Collection'), ('Birthday Cakes', 'Birthday Cakes'), ('Kids Birthday Cakes', 'Kids Birthday Cakes'), ('Christening Cakes', 'Christening Cakes'), ('Communion and Confirmation Cakes', 'Communion and Confirmation Cakes'), ('Anniversary and Occasional Cakes', 'Anniversary and Occasional Cakes'), ('Novelty Cupcakes', 'Novelty Cupcakes'), ('The Buttercream Collection', 'The Buttercream Collection'), ('Wedding Cake Tables and Wedding Cupcake Dispalys', 'Wedding Cake Tables and Wedding Cupcake Dispalys'), ('Novelty Style Wedding Cakes and Wedding Cakes with Cake Toppers', 'Novelty Style Wedding Cakes and Wedding Cakes with Cake Toppers'), ('Classic Wedding Cakes', 'Classic Wedding Cakes'), ('Elegance and Simplicity', 'Elegance and Simplicity'), ('Vintage Romantic Wedding Cakes', 'Vintage Romantic Wedding Cakes'), ('Corporate Cakes', 'Corporate Cakes'), ('Branded Cupcakes', 'Branded Cupcakes')], default=None, max_length=120),
            preserve_default=False,
        ),
    ]
