# Generated by Django 3.1.2 on 2020-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20201109_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(choices=[(1, '6"'), (2, '8"'), (3, '10"'), (4, '12"'), (5, '6"/8"'), (6, '6"/10"'), (7, '8"/10"'), (9, '4"/6"/8"'), (10, '6"/8"/10"'), (8, '8"/12"'), (11, '4"/6"/8"/10"'), (12, '6"/8"/10"/12"'), (13, '24 Cupcakes'), (14, '36 Cupcakes'), (15, '48 Cupcakes'), (16, '60 Cupcakes')], default=None, max_length=120),
        ),
    ]
