# Generated by Django 3.1.2 on 2020-10-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201025_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_cake',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
