# Generated by Django 3.1.2 on 2020-11-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201109_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cake_category',
            field=models.CharField(choices=[(1, 'Novelty Cakes'), (2, 'Wedding Cakes'), (3, 'Corporate Cakes')], default='', max_length=120),
        ),
    ]
