# Generated by Django 3.1.2 on 2020-10-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20201025_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(choices=[('8"', '8"'), ('10"', '10"'), ('12"', '12"'), ('6"/8"', '6"/8"'), ('6"/10"', '6"/10"'), ('8"/12"', '8"/12"'), ('8"/10"', '8"/10"'), ('4"/6"/8"', '4"/6"/8"'), ('6"/8"/10"', '6"/8"/10"'), ('4"/6"/8"/10"', '4"/6"/8"/10"'), ('6"/8"/10"/12"', '6"/8"/10"/12"'), ('120 cupcakes', '120 cupcakes'), ('90 cupcakes', '90 cupcakes'), ('60 cupcakes', '60 cupcakes'), ('48 cupcakes', '48 cupcakes'), ('36 cupcakes', '36 cupcakes'), ('24 cupcakes', '24 cupcakes'), ('6"', '6"')], default=None, max_length=120),
        ),
    ]
