# Generated by Django 3.1.2 on 2020-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20201109_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(choices=[('6"', '6"'), ('8"', '8"'), ('10"', '10"'), ('12"', '12"'), ('6"/8"', '6"/8"'), ('6"/10"', '6"/10"'), ('8"/10"', '8"/10"'), ('4"/6"/8"', '4"/6"/8"'), ('6"/8"/10"', '6"/8"/10"'), ('8"/12"', '8"/12"'), ('4"/6"/8"/10"', '4"/6"/8"/10"'), ('6"/8"/10"/12"', '6"/8"/10"/12"'), ('24 Cupcakes', '24 Cupcakes'), ('36 Cupcakes', '36 Cupcakes'), ('48 Cupcakes', '48 Cupcakes'), ('60 Cupcakes', '60 Cupcakes'), ('14"', '14"')], default=None, max_length=120),
        ),
    ]
