# Generated by Django 3.1.2 on 2020-11-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201109_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flavour_category',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Cup Cakes', 'Cup Cakes')], default=1, max_length=120),
            preserve_default=False,
        ),
    ]
