# Generated by Django 3.1.2 on 2020-11-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201105_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
