# Generated by Django 3.1.2 on 2020-11-15 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20201109_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavour_category',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Cup Cakes', 'Cup Cakes'), ('tier1 flavour', 'tier1 flavour')], max_length=120),
        ),
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(choices=[('6"', '6"'), ('8"', '8"'), ('10"', '10"'), ('12"', '12"'), ('6"/8"', '6"/8"'), ('6"/10"', '6"/10"'), ('8"/10"', '8"/10"'), ('4"/6"/8"', '4"/6"/8"'), ('6"/8"/10"', '6"/8"/10"'), ('8"/12"', '8"/12"'), ('4"/6"/8"/10"', '4"/6"/8"/10"'), ('6"/8"/10"/12"', '6"/8"/10"/12"'), ('24 Cupcakes', '24 Cupcakes'), ('36 Cupcakes', '36 Cupcakes'), ('48 Cupcakes', '48 Cupcakes'), ('60 Cupcakes', '60 Cupcakes'), ('14"', '14"'), ('4"/6"/8"/10"/12"', '4"/6"/8"/10"/12"'), ('8"/10"/12"', '8"/10"/12"')], max_length=120),
        ),
    ]
